// Fill out your copyright notice in the Description page of Project Settings.

#pragma once
#include "NativeGameplayTags.h"

namespace ClashGameplayTags
{
	// Input Tag //
	PROJECT_CLASH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Move);
	PROJECT_CLASH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Look);
	PROJECT_CLASH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Attack_A);
	PROJECT_CLASH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Attack_B);
	PROJECT_CLASH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_LockOn);
	PROJECT_CLASH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Input_Guard);
	// Input Tag //

	// Player Ability Tag //
	PROJECT_CLASH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Combo_X_1);
	PROJECT_CLASH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Combo_X_2);
	PROJECT_CLASH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Combo_X_3);
	PROJECT_CLASH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Combo_X_4);
	PROJECT_CLASH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Combo_Y_1);
	PROJECT_CLASH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Combo_Y_2);
	PROJECT_CLASH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Combo_Y_3);
	PROJECT_CLASH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Combo_Y_4);
	PROJECT_CLASH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Combo_Derived_X);
	PROJECT_CLASH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Combo_Derived_Y);
	PROJECT_CLASH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_LockOn);

	PROJECT_CLASH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_State_ReadyCombo_X_2);
	PROJECT_CLASH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_State_ReadyCombo_X_3);
	PROJECT_CLASH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_State_ReadyCombo_X_4);
	PROJECT_CLASH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_State_ReadyCombo_Y_2);
	PROJECT_CLASH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_State_ReadyCombo_Y_3);
	PROJECT_CLASH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_State_ReadyCombo_Y_4);
	PROJECT_CLASH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_State_ReadyCombo_Derived_X);
	PROJECT_CLASH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_State_ReadyCombo_Derived_Y);
	PROJECT_CLASH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_State_LockOn);

	PROJECT_CLASH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_ReadyToNextCombo);
	PROJECT_CLASH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_EndCombo);
	PROJECT_CLASH_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_PlayNextCombo);
	// Player Ability Tag //
}